KONJOUR_COMPILER    = "gcc"

artefacts = ["konjour", "lib1", "lib2"]

[konjour]
	c_std   = "11"
	cxx_std = "14"
	binary  = "executable"
	mode    = "release"
	output  = "bin"
	
	sources = ["src/konjour.c", "src/cfg_parser.c"]

[lib1]
	sources = ["src/fake.c"]
	libs    = ["lib2"]

[lib2]
	binary  = "static"
	sources = ["src/konjour.c", "src/cfg_parser.c"]