KONJOUR_COMPILER    = "gcc"

artefacts = ["konjour", "lib1"]

[konjour]
	c_std   = "11"
	cxx_std = "14"
	binary  = "executable"
	mode    = "release"
	output  = "bin"
	
	sources = ["src/konjour.c", "src/cfg_parser.c"]
	libs    = ["lib1"]

[lib1]
	sources = ["src/fake.cpp"]
	libs    = ["lib2"]