KONJOUR_COMPILER    = "gcc"
KONJOUR_MAKE_PREFIX = "mingw32-make"
KONJOUR_VERBOSE     = true

artefacts = ["konjour", "konjour2"]

[konjour]
	c_std   = "11"
	cxx_std = "14"
	binary  = "executable"
	mode    = "release"
	output  = "bin"
	
	sources = ["src/konjour.c", "src/cfg_parser.c"]

[konjour2]
	binary  = "static"
	sources = ["src/konjour.c", "src/cfg_parser.c"]